# Supabase CLI configuration
project_id = "ounmeqvyjjzlndbhnufk"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true

[functions.generate-script]
verify_jwt = true

[functions.summarize-script]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true
